#ifndef ZONE_ERROR_H
#define ZONE_ERROR_H

enum zone_error {
    ZONE_ERROR_OK = 0,
    ZONE_ERROR_IMPOSSIBLE,
    ZONE_ERROR_BAD_TTL,
    ZONE_ERROR_NESTED_PARENS,
    ZONE_ERROR_BAD_PARENS,
    ZONE_ERROR_ORIGIN_LONG,
    ZONE_ERROR_NAKED_CR,
    ZONE_ERROR_UNEXPECTED_TOKEN,
    ZONE_ERROR_DIRECTIVE_UNKNOWN,
    ZONE_ERROR_EXPECTED_WHITESPACE,
    ZONE_ERROR_INCLUDE_DEPTH,
    ZONE_ERROR_INCLUDE_FILENAME_MISSING,
    ZONE_ERROR_QUOTES_UNTERMINATED,
    ZONE_ERROR_PARENS_UNTERMINATED,
    ZONE_ERROR_RECORD_TOO_BIG,
    ZONE_ERROR_WIRE_OVERFLOW,
    ZONE_ERROR_EXPECTED_GENERIC,
    ZONE_ERROR_LABEL_EMPTY, /* like www..exampe.com */
    ZONE_ERROR_LABEL_LONG, /* over 63 characters */
    ZONE_ERROR_NAME_LONG, /* over 255 characters */
    ZONE_ERROR_ESCAPE_BAD, /* \DDD incorrect */
    ZONE_ERROR_TEXT_MISSING_QUOTES, /* end string quotes not found */
    ZONE_ERROR_TEXT_LONG, /* string too long */
    ZONE_ERROR_MAX,
};

const char *zone_error_msg(enum zone_error err);


#endif
